[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_BASE_URL = "https://mentorship-platform-fullstack.onrender.com/api"
  SECRETS_SCAN_OMIT_KEYS = "VITE_API_BASE_URL"
